/*
 * This source file was generated by the Gradle 'init' task
 */
package org.helmo.example.app;


import org.helmo.example.infrastructures.Repository;
import org.helmo.example.views.View;

public class Program {
    public static void main(String[] args) {
        View.greets();
        Repository.greetsFromInfra();
    }
}
