/*
 * This source file was generated by the Gradle 'init' task
 */
package org.helmo.example.app;

public class Program {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Program().getGreeting());
    }
}
